import CoreGraphics
import XCTest
@testable import NeighborhoodQuiz

/// Checks on the data file the city's centrelines are baked into. It is generated by
/// `Tools/fetch_map_data.py` and committed, so these are the tests that would catch a
/// bad re-fetch — a dataset that moved, a filter that swallowed a borough, an
/// abbreviation the speller does not know. `BrooklynMapDataTests` is the twin, for the
/// other file.
final class ManhattanMapDataTests: XCTestCase {
    private let map = BoroughMap.of(.manhattan)

    func testTheFileIsThereAndHasAnIsland() {
        let land = map.land
        XCTAssertFalse(land.isEmpty, "manhattan.json did not load")

        // Manhattan, Randalls, Roosevelt and the scrap of Marble Hill.
        XCTAssertGreaterThanOrEqual(land.count, 1)
        XCTAssertLessThanOrEqual(land.count, 8, "Governors and Ellis should be filtered out")

        let island = land.max { $0.count < $1.count } ?? []
        XCTAssertGreaterThan(island.count, 150, "The island is too coarse to read as Manhattan")
        XCTAssertLessThan(island.count, 900, "And too fine to stroke on every frame")
    }

    func testTheIslandIsWhereManhattanIs() {
        for ring in map.land {
            for point in ring {
                XCTAssertTrue((-74.03...(-73.90)).contains(point.longitude), "\(point) is not in the harbour")
                XCTAssertTrue((40.69...40.90).contains(point.latitude), "\(point) is not in the harbour")
            }
        }
    }

    func testTheIslandDoesNotCrossItself() {
        // Thinning a 4,785-point shoreline down to a few hundred can fold it over on
        // itself, and a folded ring fills as a mess. The city's own outline is sound;
        // this is a check on what the tool does to it.
        let island = map.land.max { $0.count < $1.count } ?? []
        let points = island.map { CGPoint(x: $0.longitude * 10_000, y: $0.latitude * 10_000) }

        for i in 0..<points.count {
            let a = points[i]
            let b = points[(i + 1) % points.count]
            for j in (i + 1)..<points.count {
                if j == i || j == (i + 1) % points.count || (j + 1) % points.count == i { continue }
                XCTAssertNil(
                    Polyline.crossing(a, b, points[j], points[(j + 1) % points.count]),
                    "Shoreline edge \(i) crosses edge \(j)"
                )
            }
        }
    }

    func testEveryRoadHasSomethingToDrawAndAName() {
        let roads = map.roads
        XCTAssertGreaterThan(roads.count, 1_000, "The whole island should be in here")
        for road in roads {
            XCTAssertGreaterThanOrEqual(road.coordinates.count, 2, "\(road.name) has no line")
            XCTAssertFalse(road.name.isEmpty)
        }
    }

    func testEveryStreetIsNamedExactlyOnce() {
        // A street the city stores in pieces comes back as several runs; exactly one of
        // them carries the name, or Broadway would be written on the map eighteen times.
        var carriers: [String: Int] = [:]
        for road in map.roads where road.carriesName {
            carriers[road.name, default: 0] += 1
        }
        let doubled = carriers.filter { $0.value > 1 }
        XCTAssertTrue(doubled.isEmpty, "written more than once: \(doubled.keys.sorted())")

        let named = Set(map.roads.map(\.name))
        XCTAssertEqual(carriers.count, named.count, "every street gets its name somewhere")
    }

    func testTheStreetsBelowHoustonAreActuallyThere() {
        // The whole point of the city's data: the grid gives out below Houston and the
        // streets there have names and no pattern. None of these can be generated.
        let named = Set(map.roads.map(\.name))
        for street in [
            "Mercer Street", "Prince Street", "Spring Street", "Bleecker Street",
            "Mulberry Street", "Orchard Street", "Ludlow Street", "Pearl Street",
            "Wall Street", "Canal Street", "Bowery", "Christopher Street",
        ] {
            XCTAssertTrue(named.contains(street), "\(street) is missing from the map")
        }
    }

    func testTheAvenuesRankAboveTheSideStreets() {
        let byKind = Dictionary(grouping: map.roads, by: \.kind)
        let avenues = Set((byKind[.avenue] ?? []).map(\.name))
        for expected in [
            "Broadway", "Fifth Avenue", "Park Avenue", "Madison Avenue", "Lexington Avenue",
            "Amsterdam Avenue", "Central Park West", "Second Avenue", "West End Avenue",
        ] {
            XCTAssertTrue(avenues.contains(expected), "\(expected) should rank as an avenue")
        }
        XCTAssertGreaterThan((byKind[.side] ?? []).count, (byKind[.avenue] ?? []).count,
                             "Most of Manhattan is side streets")
    }

    func testAHighwayIsNotAnAvenueAndNorIsACarriageDrive() {
        // Rank comes from length, and the longest roads on the island are not the ones
        // anybody gives directions by. The Henry Hudson and the FDR are highways; West
        // Drive and East Drive are long because they wander through Central Park. All
        // four outranked Madison Avenue before the roadway type and the greens were
        // brought in to sort them out.
        let avenues = Set(map.roads.filter { $0.kind == .avenue }.map(\.name))
        for pretender in [
            "Henry Hudson Parkway", "Franklin D Roosevelt Drive", "Harlem River Driveway",
            "West Street", "West Drive", "East Drive",
        ] {
            XCTAssertFalse(avenues.contains(pretender), "\(pretender) should not rank as an avenue")
        }
    }

    func testALeadingStIsSaintAndNotStreet() {
        let named = Set(map.roads.map(\.name))
        XCTAssertTrue(named.contains("St. Nicholas Avenue"))
        XCTAssertTrue(named.contains("St. Marks Place"))
        XCTAssertFalse(named.contains("Street Nicholas Avenue"))
        // But ST anywhere else really is the street it looks like.
        for name in named {
            XCTAssertFalse(name.hasPrefix("Street "), "\(name) read a Saint as a Street")
        }
    }

    func testTheNamesAreSpeltTheWayPeopleWriteThem() {
        let named = Set(map.roads.map(\.name))
        // A numbered avenue is spelled out; a numbered street keeps its figures.
        XCTAssertTrue(named.contains("Fifth Avenue"))
        XCTAssertTrue(named.contains("42nd Street") || named.contains("East 42nd Street"))
        XCTAssertFalse(named.contains("5 AVE"))

        for name in named {
            XCTAssertFalse(name.contains("  "), "\(name) has the city's double space in it")
            XCTAssertEqual(name, name.trimmingCharacters(in: .whitespaces))
            // Left-over abbreviations mean the speller met something it does not know.
            for stump in [" St", " Ave", " Pl", " Blvd", " Dr", " Pkwy", " Hl", " Dy"] {
                XCTAssertFalse(name.hasSuffix(stump), "\(name) was not spelled out")
            }
        }
    }

    func testTheRampsAndServiceRoadsAreLeftOut() {
        for road in map.roads {
            let name = road.name.uppercased()
            for plumbing in [" EN ", " EX ", " NB ", " SB ", "OPAS", "RAMP"] {
                XCTAssertFalse(name.contains(plumbing), "\(road.name) is highway plumbing, not a street")
            }
        }
    }

    func testCentralParkIsAmongTheGreens() {
        let parks = map.parks
        XCTAssertGreaterThan(parks.count, 10)
        XCTAssertTrue(parks.contains { $0.name.localizedCaseInsensitiveContains("Central Park") })
        for park in parks {
            XCTAssertGreaterThanOrEqual(park.ring.count, 3, "\(park.name) is not a shape")
        }
    }

    func testTheNeighbourhoodsAreNotOnTheMapYet() {
        // The point of the quiz is that the map does not tell you. A street may be
        // named after a district — Chelsea has a Chelsea Place — so this checks the
        // greens and the streets for names that are *only* a neighbourhood.
        let forbidden = ["SoHo", "Tribeca", "Harlem", "Midtown", "Greenwich Village"]
        for road in map.roads {
            for name in forbidden {
                XCTAssertNotEqual(road.name.lowercased(), name.lowercased())
            }
        }
    }

    func testTheSourceIsCredited() {
        XCTAssertTrue(map.source.contains("NYC Open Data"))
    }

    // MARK: - The neighbourhoods

    func testTheIslandIsDividedIntoNeighborhoods() {
        let areas = map.neighborhoods
        XCTAssertEqual(areas.count, 40, "`AREAS` in fetch_map_data.py names forty")

        for area in areas {
            XCTAssertFalse(area.name.isEmpty)
            XCTAssertFalse(area.rings.isEmpty, "\(area.name) has no shape")
            for ring in area.rings {
                XCTAssertGreaterThanOrEqual(ring.count, 3, "\(area.name) has a ring that is a line")
            }
        }

        let names = areas.map(\.name)
        XCTAssertEqual(Set(names).count, names.count, "Two neighborhoods share a name")
    }

    func testTheNeighborhoodsAreWhereManhattanIs() {
        for area in map.neighborhoods {
            for point in area.rings.flatMap({ $0 }) {
                XCTAssertTrue((-74.03...(-73.90)).contains(point.longitude), "\(area.name) is in the harbour")
                XCTAssertTrue((40.69...40.90).contains(point.latitude), "\(area.name) is in the harbour")
            }
        }
    }

    func testNoNeighborhoodCrossesItself() {
        // The same fold that turned Wards Island into a bow tie would turn a
        // neighborhood into one, and a folded ring both fills wrong and hit tests wrong.
        for area in map.neighborhoods {
            for (index, ring) in area.rings.enumerated() {
                let points = ring.map { CGPoint(x: $0.longitude * 10_000, y: $0.latitude * 10_000) }
                for i in 0..<points.count {
                    let a = points[i]
                    let b = points[(i + 1) % points.count]
                    for j in (i + 1)..<points.count {
                        if j == i || j == (i + 1) % points.count || (j + 1) % points.count == i { continue }
                        XCTAssertNil(
                            Polyline.crossing(a, b, points[j], points[(j + 1) % points.count]),
                            "\(area.name) ring \(index) folds over itself at \(i)/\(j)"
                        )
                    }
                }
            }
        }
    }

    func testTheFewNeighborhoodsThatComeInPiecesStillDo() {
        // The Financial District takes in the piers along both rivers, which the city
        // counts as its ground but which no walk connects to the rest of it. A re-fetch
        // that quietly kept only the first ring of each area would still look right at a
        // glance and would be wrong here.
        XCTAssertGreaterThan(named("Financial District")?.rings.count ?? 0, 1)
    }

    /// Splitting the compound names was the point of building these out of tracts rather
    /// than taking the city's areas whole. This is the check that they stayed split: the
    /// city has no "SoHo", only "SoHo-Little Italy-Hudson Square", and a re-fetch that
    /// fell back to the NTA table would pass every other test in this file.
    func testTheNamesAreOnesAPlayerWouldSay() {
        for name in [
            "SoHo", "Little Italy", "Hudson Square", "Tribeca", "Civic Center",
            "Chinatown", "Two Bridges", "Financial District", "Battery Park City",
            "Alphabet City", "Flatiron", "NoMad", "Union Square", "Times Square",
            "Midtown East", "Turtle Bay", "Hudson Yards", "Chelsea", "Roosevelt Island",
            "Murray Hill", "Kips Bay", "Sugar Hill", "Hamilton Heights",
            "Harlem", "East Harlem", "Washington Heights", "Upper East Side",
            "Upper West Side",
        ] {
            XCTAssertNotNil(named(name), "\(name) is missing from the map")
        }

        // And no name is one of the city's compounds, which is what this pass was for.
        for area in map.neighborhoods {
            XCTAssertFalse(
                area.name.contains("-") && area.name.contains(" "),
                "\(area.name) still reads like an NTA rather than like a place"
            )
            XCTAssertFalse(area.name.contains("("), "\(area.name) still has a qualifier on it")
        }
    }

    /// Roosevelt Island is filed by the city under Lenox Hill. It is an island in the
    /// East River reached by a tram, and a player told it was the Upper East Side would
    /// be right to argue, so it is pulled out into its own area — and being its own area
    /// means it must not also be part of the Upper East Side's.
    func testRooseveltIslandIsNotTheUpperEastSide() {
        guard let island = named("Roosevelt Island"), let upper = named("Upper East Side") else {
            return XCTFail("Both areas should exist")
        }
        let east = island.rings.flatMap { $0 }.map(\.longitude).min() ?? 0
        XCTAssertGreaterThan(east, -73.97, "Roosevelt Island is in the river, not on the island")

        for point in island.rings.flatMap({ $0 }) {
            for ring in upper.rings {
                XCTAssertFalse(
                    Self.ring(ring, contains: point),
                    "\(point) is claimed by both Roosevelt Island and the Upper East Side"
                )
            }
        }
    }

    private func named(_ name: String) -> BoroughMap.Neighborhood? {
        map.neighborhoods.first { $0.name == name }
    }

    private static func ring(_ ring: [Coordinate], contains point: Coordinate) -> Bool {
        var inside = false
        var previous = ring.count - 1
        for index in ring.indices {
            let a = ring[index], b = ring[previous]
            if (a.latitude > point.latitude) != (b.latitude > point.latitude) {
                let cut = (b.longitude - a.longitude) * (point.latitude - a.latitude)
                    / (b.latitude - a.latitude) + a.longitude
                if point.longitude < cut { inside.toggle() }
            }
            previous = index
        }
        return inside
    }
}
