default_platform(:ios)

platform :ios do

  before_all do
    setup_ci if ENV['CI']
  end

  desc "Run tests"
  lane :test do
    scan(
      project: "NeighborhoodQuiz.xcodeproj",
      scheme: "NeighborhoodQuiz",
      device: "iPhone 17",
      clean: true
    )
  end
end
